services:
    mysql:
        image: mysql:8.0
        container_name: kiroku-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: kiroku
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: kiroku_user
            MYSQL_PASSWORD: kiroku_password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        networks:
            - kiroku-network
        command: --default-authentication-plugin=mysql_native_password

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: kiroku-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8081:80"
        depends_on:
            - mysql
        networks:
            - kiroku-network

volumes:
    mysql_data:
        driver: local

networks:
    kiroku-network:
        driver: bridge
